version: "3.8"

services:
  web:
    image: ghcr.io/alexander738022/proyecto:3.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/tareas_db
    networks:
      - webnet

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tareas_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  proxy:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@erick.byronrm.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - webnet

networks:
  webnet:

volumes:
  pgdata:
  letsencrypt:
